version: '3'
services:
  customers-service:
    build:
      context: ../customers-service/
      args:
        baseImageVersion: ${EVENTUATE_JAVA_BASE_IMAGE_VERSION?}
    ports:
      - "8081:8080"
    environment:
      EVENTUATEDATABASE: mysql
      QUARKUS_DATASOURCE_USERNAME: mysqluser
      QUARKUS_DATASOURCE_PASSWORD: mysqlpw
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://mysql/eventuate
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

networks:
  default:
    external:
      name: eventuate-quarkus-examples-customers-and-orders_default