version: '3'
services:
  customers-service:
    build:
      context: ../customers-service/
      args:
        baseImageVersion: ${EVENTUATE_JAVA_BASE_IMAGE_VERSION?}
    ports:
      - "8081:8080"
    environment:
      EVENTUATEDATABASE: postgresql
      QUARKUS_DATASOURCE_USERNAME: eventuate
      QUARKUS_DATASOURCE_PASSWORD: eventuate
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://$DOCKER_HOST_IP/eventuate
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: $DOCKER_HOST_IP:9092
