version: '3'
services:
  customercommandside:
    build:
      context: ../customers-service/
      args:
        baseImageVersion: ${EVENTUATE_JAVA_BASE_IMAGE_VERSION?}
    ports:
      - "8081:8080"
    environment:
      DB_URL: jdbc:postgresql://$DOCKER_HOST_IP/eventuate
      DB_USERNAME: eventuate
      DB_PASSWORD: eventuate
      DB_DRIVERCLASSNAME: org.postgresql.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: $DOCKER_HOST_IP:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: $DOCKER_HOST_IP:2181
