version: '3'
services:
  customercommandside:
    build:
      context: ../customers-service/
      args:
        baseImageVersion: ${EVENTUATE_JAVA_BASE_IMAGE_VERSION?}
    ports:
      - "8081:8080"
    environment:
      EVENTUATEDATABASE: mysql
      QUARKUS_DATASOURCE_USERNAME: mysqluser
      QUARKUS_DATASOURCE_PASSWORD: mysqlpw
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://${DOCKER_HOST_IP}/eventuate
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: ${DOCKER_HOST_IP}:9092
